### ISSUE TITLE
[FEATURE_REQUEST] Non-exact dates

### ISSUE THREAD

**Issue by DementedDuckling** [mateusz-bak/openreads#247]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
To be able to enter dates not following the month/day/year format and only list the year, the month and the year, etc. It would help when readers are unable to recall full dates, but still want to keep track of what they know, especially in graphs.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mateusz-bak** [comment]
Hi! I analyzed the issue and I think it would be too much to implement for what is to be gained here.

The dates need to have exact year, month and day. So if we wanted to make it non exact it would still need to point to something like 1st day of the month or 1st month of the year.

If we did not do that then sorting would be impacted.

And UI would also be cluttered a lot as we have multi reading dates now.

So my suggestion is to just set the 1st day of the month or Jan 1st for a year.
