### ISSUE TITLE
[FEATURE_REQUEST] Add a Counter, for each time you read the book

### ISSUE THREAD

**Issue by Spleezzer** [mateusz-bak/openreads#260]
**Describe the solution you'd like**
I would like to have the possibillity to count and see how often I read a book. A already read book could be marked as "reading" and if it is finished, it is marked as "read two times".

**Describe alternatives you've considered**
A little number on the book info page would be nice.

**Comment by apobrt** [comment]
Related to #87 .
But I like the idea of also displaying the counter
