### ISSUE TITLE
[FEATURE_REQUEST] Keep track of owned books

### ISSUE THREAD

**Issue by acbarker19** [mateusz-bak/openreads#417]
**Is your feature request related to a problem? Please describe.**
This may be out of the intended scope of this app, but it could be a useful feature for users to keep track of the books that they own. When users have a large number of books they are keeping track of, having a way to see owned books would help them determine if they need to look at their bookshelf or if they need to buy or rent the book.

**Describe the solution you'd like**
When adding a book to one of the lists in the user's library, there could be a toggle (either a switch or a checkbox) to indicate that the user owns the book. There could then be a new filter to search for owned books on each of the existing lists, and there could also possibly be a new list altogether for displaying owned books.

**Describe alternatives you've considered**
This could be achieved through the existing tags system, but a unique toggle seems more apparent and helps prevent possible typos while marking it as owned. If it is easier for implementation, the existing tag system may even be able to be utilized for filtering if there is a way to create a "hidden" ownership tag.

**Additional context**
Thank you for taking a look at this suggestion! Please let me know if there are any questions about the proposal.

**Comment by apobrt** [comment]
I thought an extra alternative: maybe create an always present tag like "in library" or "owned", so it uses the tag system, but it's more "official" (and prevent typos).
What do you think @mateusz-bak ?

**Comment by mateusz-bak** [comment]
I think the adding book page is already overcrowded (and I'm currently making it even more messy with multiple read dates) but I have no idea how to fix the UX there, so I wouldn't want to see another toggle for owned books there.
But @apobrt 's ideas makes good sense to auto add the `owned` tag. I think this will solve the issue, be consistent and will not clutter the UI more.

**Comment by mateusz-bak** [comment]
Added auto tag `owned` for new books (can be unselected)

**Comment by ikanakova** [comment]
Would it be possible to make it optional if the `owned` tag is automatically added for new books?
