### ISSUE TITLE
[FEATURE_REQUEST]  Add "Date Added" and "Date Updated" sort options

### ISSUE THREAD

**Issue by visuelledata** [mateusz-bak/openreads#419]
**Is your feature request related to a problem? Please describe.**
When you add a book to "For Later" it is because you're actively interested in the book. When I go to "Read later" I would like to see books that I'm currently interested in.

**Describe the solution you'd like**
When I go to read later, I want to see the books that are most recently added

**Describe alternatives you've considered**
I'm not aware of any alternatives.

**Additional context**
I would personally prefer that #150 be prioritized over this.

**Comment by visuelledata** [comment]
Edited the description because I didn't realize that I hadn't changed it earlier

**Comment by mateusz-bak** [comment]
Added date added, date modified and sorting by those two
