### ISSUE TITLE
[FEATURE_REQUEST] Sort tags attached to a book alphabetically

### ISSUE THREAD

**Issue by Phaaxood** [mateusz-bak/openreads#420]
**Is your feature request related to a problem? Please describe.**
I only started to use the app and currently use tags to annotate the language a book is written in, the type of book, the series a book might be part of, whether I own or rented it. Visually checking in the book list whether I added all tags or not, especially for the books in a series that should basically all have the same tags, is made difficult by the tags being sorted in the order they were attached to the book. That order has no semantic meaning - at least for me.

**Describe the solution you'd like**
Sorting the tags attached to a book alphabetically provides a faster way to visually process the tags in the books list.

**Describe alternatives you've considered**
There might be other ways to consistently sort the tags attached to a book that offer other benefits. Basically any consistent sorting of the tags addresses my problem.

**Comment by mateusz-bak** [comment]
I agree - it shoule be consistent and sorting it alphabetically makes the most senss.
