### ISSUE TITLE
[FEATURE_REQUEST] Increase maximum tag length to accomodate series titles

### ISSUE THREAD

**Issue by Phaaxood** [mateusz-bak/openreads#421]
**Is your feature request related to a problem? Please describe.**
I'm using tags to group books that belong to the same series, as suggested in #343 and #187. With the current maximum tag length of 20 characters, this sometimes poses a challenge for longer series titles - as far as I saw the title of a book itself is allowed to be 255 characters. To group tags and differentiate between categories and series, I currently use 'hierarchical tags' like 'series/<series title>' to have them stand out, which does not help with the length limit.

**Describe the solution you'd like**
Increasing the maximum tag length to something like 50 characters should provide enough space for this use case.

**Describe alternatives you've considered**
An alternative would be providing a field to explicitly group titles in a series like originally suggested in #343. That could also be used to group series in the list of books to provide more structure. Books in the series could be shown next to each other, irrespective of their individual title. Optionally, a single cover might be shown as a stand in for all books in the group, linking to a filtered list of the individual entries.

**Comment by lucastucious** [comment]
Upvote this issue, as I have the same issue

**Comment by mateusz-bak** [comment]
Simple increase in the tag's lenght limit should be ok, will change it.

**Comment by mateusz-bak** [comment]
Implemented, tag limit increased to 100 and will be displayed in multiple lines if needed.
