### ISSUE TITLE
[BUG] Keyboard does not hide on non textfield tap

### ISSUE THREAD

**Issue by th8m0z** [mateusz-bak/openreads#439]
**Describe the bug**
It's difficult to hide the keyboard when editing book details on devices where there is no hide keyboard attached to the keyboard.

**To Reproduce**
Open the app on the iOS simulator, edit any text element of the book details, for example subtitle and try to dismiss the keyboard.

**Expected behavior**
Tapping on a non-text field element on the page should dismiss the keyboard.

**Screenshots**
![simulator_screenshot_6A093AFF-D1E8-46B0-B5A2-A3AB391038D3](https://github.com/mateusz-bak/openreads-android/assets/41947147/915d082d-f9d6-420e-983d-833bd6fe33d9)

**Additional info(please complete the following information):**
- App version: 2.3.0
- App source (F-Droid, Google Play, Github, AppStore): Github
- Manufacturer and model: iPhone 15 Pro
- OS and version: iOS 17.0

**Additional context**
I can work on this issue.

**Comment by mateusz-bak** [comment]
Good spot, we could add something like keyboard dismissable area (not sure how this is called). And if you want to work on this - awesome :rocket:

**Comment by th8m0z** [comment]
Added a PR https://github.com/mateusz-bak/openreads-android/pull/442
