### ISSUE TITLE
[BUG] Overflow problems on devices with different resolutions & different locales

### ISSUE THREAD

**Issue by th8m0z** [mateusz-bak/openreads#443]
**Describe the bug**
On multiple pages we can see overflow problems that are either due to text or widgets not dynamically resizing, since different devices less space and certain locales require more text.

**To Reproduce**
Use the iPhone 15 Pro Simulator to go to the "Search Open Library" page, using the German locale.

**Expected behavior**
No overflows.

**Screenshots**
![simulator_screenshot_FEB4D8ED-E033-431B-AB07-14D35448B913](https://github.com/mateusz-bak/openreads-android/assets/41947147/9b9f14c3-7049-4d2f-a342-2a2cab71baf1)
![simulator_screenshot_27D53B39-4BE1-4D8C-9AE2-59688309C4DD](https://github.com/mateusz-bak/openreads-android/assets/41947147/a9a858b6-a77f-46cc-8878-12cdecace89b)

**Additional info(please complete the following information):**
- App version:  2.4.0+48
- App source: Github
- Manufacturer and model: iPhone 15 Pro Simulator
- OS and version: iOS 17.0

**Additional context**
I would be able to work on this, and my proposal is to make the Text widgets AutoSizeText, add Flexibles in some places and maybe even implement https://pub.dev/packages/responsive_framework, as it does not require any hardcoded text sizes to change as far as I can tell.

**Comment by mateusz-bak** [comment]
Nice, go for it! In the places like the search OL filters you can use Wrap Widget I think.

**Comment by mateusz-bak** [comment]
In the some latest changes I added wrapping fot the "Welcome in Openreads" text in welcome screen

**Comment by mateusz-bak** [comment]
Do you want me to assign this bug to you @th8m0z ?

**Comment by th8m0z** [comment]
Yes definitely!

**Comment by mateusz-bak** [comment]
@th8m0z how is this going?

**Comment by th8m0z** [comment]
Going good, will add a PR soon.
