### ISSUE TITLE
[BUG] When adding a tag, list of proposed tags is not filtered

### ISSUE THREAD

**Issue by mateusz-bak** [mateusz-bak/openreads#453]
**Describe the bug**
Tags prediction list is not filtered by typing text. It just shows list of all tags.

**To Reproduce**
Start typing a new tag name in Edit Book Screen.

**Expected behavior**
A list of tags is shown and being filtered after user types more letters.

**Additional info(please complete the following information):**
- App version: 2.4.1
- App source (F-Droid, Google Play, Github, AppStore): Github
- Manufacturer and model: OnePlus 8T
- OS and version: Android 13

**Additional context**
@apobrt do you want to take this?

**Comment by Mohit-Joshi-dev** [comment]
@mateusz-bak Is this still open to work on, can I take this?

**Comment by mateusz-bak** [comment]
Of course, go for it @Mohit-Joshi-dev

**Comment by Mohit-Joshi-dev** [comment]
@mateusz-bak I have raised a pull request for this issue, please check.
Thanks!

P.S. It was fun to work on this.
