### ISSUE TITLE
[BUG] Sort by number of pages is lexicographic

### ISSUE THREAD

**Issue by leopoldfajtak** [mateusz-bak/openreads#463]
**Describe the bug**
If you sort books by number of pages, the lexicographical order of the numbers of pages is used instead of the numeric value. This makes a difference if the page numbers have various amounts of digits.

**To Reproduce**
- Add a book with 10 pages
- Add a book with 110 pages
- Add a book with 20 pages
- Order by page number

**Expected behavior**
The ordering should be 10, 20, 110

**Additional info(please complete the following information):**
- App version: 2.4.1
- App source (F-Droid, Google Play, Github, AppStore): F-Droid
- Manufacturer and model:
- OS and version: CalyxOS 5.4.0

**Additional context**

**Comment by mateusz-bak** [comment]
Thanks for reporting, will be fixed in 2.5.0
