### ISSUE TITLE
[BUG] No import of subtitle when adding a book from OpenLibrary

### ISSUE THREAD

**Issue by Kazing** [mateusz-bak/openreads#468]
**Describe the bug**
Not sure if its a bug or a feature missing.
When i search a book in Open Library, then add it, the "Add a new book" page contain the title, the cover, number of pages, year, description. But the "subtitle" field is empty even if the book as a subtitle in Open Library.
When the book is added in my app the subtitles is also empty.

**To Reproduce**
1. Click "Search in Open Library"
2. Type "Pour la sociologie Lahire"
3. Click "Add" on the eponymous book
4. See the "Add a new book" page with empty Subtitle field
5. Add the book, and see that there is no subtitle

Link to this book in OL : https://openlibrary.org/works/OL17335916W/Pour_la_sociologie

**Expected behavior**
When a book has subtitle in Open Library, this field should be filled with the subtitles. Since the data is available in OL, it should be displayed in Openreads

**Screenshots**
/

**Additional info(please complete the following information):**
- App version: 2.4.1
- App source (F-Droid, Google Play, Github, AppStore): F-Droid
- Manufacturer and model: Pixel 4a
- OS and version: Android 13

**Additional context**
/

**Comment by mateusz-bak** [comment]
Thanks for reporting and providing and example - this should be easy to fix

**Comment by mateusz-bak** [comment]
There might be a workaround as proposed in https://github.com/internetarchive/openlibrary/issues/8144#issuecomment-1659016242

I'll try to implement something like this and test whether it works correctly.

**Comment by mateusz-bak** [comment]
In the search query when we have list of books the data does not include the subtitle even with the workaround unfortunately. It is included in the edition results but it would be good to get it as well when no edition is chosen.

Somwehow on the url you provided for the `work` the subtitle is there and it is taken from the edition. So I'm not sure how this works, and asked a question to help with clarification here https://github.com/internetarchive/openlibrary/issues/8144#issuecomment-1945960503

**Comment by Kazing** [comment]
Wow, thanks for the quick fix ! 👍
