### ISSUE TITLE
[FEATURE_REQUEST] Optional default fields of a new book

### ISSUE THREAD

**Issue by ikanakova** [mateusz-bak/openreads#470]
**Is your feature request related to a problem? Please describe.**
When a new book is added (manually / searched) the default state is Finished.
The default type for the new book is paperback.

**Describe the solution you'd like**
It would be great if the user could set the default status of newly added books (Finished / In progress / For later).
And default type of book (Paperback / Hardcover / E-Book / Audiobook)

**Describe alternatives you've considered**
When adding new books, no status and type (binding) would set up automatically and the person would have to specify it themselves.

**Additional context**

**Comment by mateusz-bak** [comment]
Thank you for reporting!

In the 1.0 version we had a feature that the book status was set depending where user was when starting adding a new book (which list of books was open). So now I re-implemented the feature I hope it will be easier now and intuitive!

And I added an option in settings to set default book format for new books.
