### ISSUE TITLE
[BUG] Incorrect statistics displayed

### ISSUE THREAD

**Issue by exstntlmsnthrp** [mateusz-bak/openreads#472]
**Describe the bug**
When viewing the statistics of my current books, it displays incorrect data. In this specific instance, the statistics state that book "X" has 815 pages, when in reality, multiple books have that many pages and two additional books, for example, books "y" and "z" have more pages. 

**To Reproduce**
View statistics. 
View longest book. 
Add a book with more pages. 
View statistics again. 

**Expected behavior**
I would expect that: a) all books with a specific page length are listed, if multiple books are the same length; b) that statistics are updated when new data is added. 

**Screenshots**
![Screenshot_20240215-094348.png](https://github.com/mateusz-bak/openreads/assets/57594290/f4dab539-a58e-4b68-b5d6-6712067802d8)

Another book with similar page length. 
![Screenshot_20240215-094828.png](https://github.com/mateusz-bak/openreads/assets/57594290/ac365c06-a531-4053-95b1-13dbf774bb6f)

A book with more pages. 
![Screenshot_20240215-094844.png](https://github.com/mateusz-bak/openreads/assets/57594290/c3396f8e-5553-441a-bbf5-f970fec67638)

Another book with even more pages. 
![Screenshot_20240215-094921.png](https://github.com/mateusz-bak/openreads/assets/57594290/cd2ff9a5-876e-4841-b546-9941b074f54c)

**Additional info(please complete the following information):**
- App version: 2.4.1
- App source (F-Droid, Google Play, Github, AppStore): GitHub
- Manufacturer and model: Google Pixel 7 Pro 
- OS and version: Android 14

**Additional context**
I have tried clearing the app cache and I have tried uninstalling, reinstalling, and importing a saved database. 

If you need/want any additional information, please let me know.

**Comment by mateusz-bak** [comment]
Thanks for reporting!

The all time statistics was not counting finished books that do not have finish dates set. I think this was causing this problem.

Fixed it now and soon you can check the results in 2.5.0.
