### ISSUE TITLE
[BUG] Old cover is presented after editing current cover

### ISSUE THREAD

**Issue by mateusz-bak** [mateusz-bak/openreads#483]
**Describe the bug**
When user edits current cover and saves the book the cover is not updated in Book Screen but it displays the old one before editing.

**To Reproduce**
1. Open Book Screen of book that has cover
2. Edit book
3. Click on cover, click on edit current cover
4. Edit the cover, for example crop it
5. Save the cover
6. Save the book
7. User is now redirected to Book Screen, but the cover is not updated (same in books list)
8. Restart the app, cover is now updated.

**Expected behavior**
Cover is updated everywhere after saving the book.

**Additional info(please complete the following information):**
- App version:  2.5.0
- App source (F-Droid, Google Play, Github, AppStore): Github
- Manufacturer and model: OnePlus 8T
- OS and version: Android 13

**Comment by exstntlmsnthrp** [comment]
I just had this happen a few days ago. Unfortunately, I don't remember what book it was, but do remember the book was being added from open library. All other fields for the book were correct, except the cover. 

What ended up working was save the book and then edit it and that accepted the new cover photo.

**Comment by mateusz-bak** [comment]
As a fix now after editing cover the app clears all image files cache so the new cover is properly loaded.
