### ISSUE TITLE
[FEATURE_REQUEST] Scan book's barcode when adding/editing

### ISSUE THREAD

**Issue by mateusz-bak** [mateusz-bak/openreads#488]
**Is your feature request related to a problem? Please describe.**
User has to manually type ISBN when adding book manually.

**Describe the solution you'd like**
Add button near ISBN field to open barcode scanner and load the ISBN

**Describe alternatives you've considered**
Manual work

**Additional context**

**Comment by Mohit-Joshi-dev** [comment]
Hey @mateusz-bak, Anyone working on this, I would like to contribute here.
