### ISSUE TITLE
[BUG] Screen jitter on edit screen when reading date section is displayed

### ISSUE THREAD

**Issue by pandalamp** [mateusz-bak/openreads#501]
**Describe the bug**
A screen jitter occurs on input when using the edit page if the reading date boxes are displayed. 

**To Reproduce**
Press the Capture Reading button on the edit page to show the date boxes and then add text to any field below the date section, or above it while the boxes are visible on screen. 

**Screenshots**
https://github.com/mateusz-bak/openreads/assets/65859489/02cce429-1d32-4f42-93d4-b88a2f183694

**Additional info(please complete the following information):**
- App version: 2.5.0
- App source F-Droid, Google Play
- Manufacturer and model: Google Pixel 7
- OS and version: Android 14

**Additional context**
I thought this might be related to input method and tested with different keyboards with no change.

**Comment by mateusz-bak** [comment]
Thanks, will take a look

**Comment by mateusz-bak** [comment]
Each change in the edit forms would cause the readings to rebuild due to re-initializing date's format each time.

I moved the date format initialization to main file so it is done only once and is not re-initialized again.

Will be released in 2.5.1

**Comment by pandalamp** [comment]
> Each change in the edit forms would cause the readings to rebuild due to re-initializing date's format each time.
> 
> I moved the date format initialization to main file so it is done only once and is not re-initialized again.
> 
> Will be released in 2.5.1

Awesome! Thank you for the explanation and the fix! 🐼
