### ISSUE TITLE
[BUG] Multiple text fields selectable simultaneously 

### ISSUE THREAD

**Issue by pandalamp** [mateusz-bak/openreads#511]
**Describe the bug**
_This is a very minor visual bug! It does not impact functionality!_ I noticed when viewing the book pages that selecting/highlighting text in one section will not clear existing selections/highlights from another section.

Only one highlight can exist at a time per field, but multiple highlights from various fields (including titles) can show at the same time. The context actions for highlighted text (copy, share, etc) only work with the most recent text selected, making this only a visual issue. 

**To Reproduce**
Click a book from any list to view its details and select/highlight text from multiple sections (title, description, ISBN, notes, etc). 

**Expected behavior**
Existing selections/highlights should be cleared when a new one is made. 

**Screenshots**
![Imagepipe_0](https://github.com/mateusz-bak/openreads/assets/65859489/d6407e7f-4091-4d95-9fde-9e55e1969aae)

**Additional info(please complete the following information):**
- App version: 2.5.1
- App source: F-Droid, Google Play
- Manufacturer and model: Pixel 7
- OS and version: Android 14.

**Comment by mateusz-bak** [comment]
Thanks, I need to improve text selecting in the app.

**Comment by mateusz-bak** [comment]
Wll be fixed in the next release.

**Comment by pandalamp** [comment]
Awesome! I love seeing your changes. Incredible work, thank you so much! 🐼
