### ISSUE TITLE
[BUG] Book without finish date are not correctly shown in list view if books sorted by finish date

### ISSUE THREAD

**Issue by MdAmine** [mateusz-bak/openreads#520]
**Describe the bug**
Book without finish date are not correctly shown in list view if books sorted by finish date.

**To Reproduce**
Add a book manually, set a start date, and let the finish date empty.
Chose the list view (not the grid view) and sort books with finish date.

**Screenshots**
![ph](https://github.com/mateusz-bak/openreads/assets/18504601/298e2c29-a1da-4405-96d3-47b0070786d1)

**Additional info(please complete the following information):**
- App version: 2.5.1
- App source: F-Droid
- Manufacturer and model: Samsung S9
- OS and version: A14

**Comment by mateusz-bak** [comment]
Hi, duplicate od #451. Will be fixed in new release
