### ISSUE TITLE
[FEATURE_REQUEST] Pick random book from list

### ISSUE THREAD

**Issue by CyberRooke** [mateusz-bak/openreads#533]
Is it possible to have a feature on the app that selects a random book from your list?

**Comment by mateusz-bak** [comment]
Thanks for the suggestion @CyberRooke ! Right now, I'm aiming to keep things simple for everyone, so I'll have to pass on the random book picker. But hey, I'm all ears for any other ideas you might have!

**Comment by CyberRooke** [comment]
> Thanks for the suggestion @CyberRooke ! Right now, I'm aiming to keep things simple for everyone, so I'll have to pass on the random book picker. But hey, I'm all ears for any other ideas you might have!

No worries... thanks for the reply 🙏🙏 and thanks for this great app 👌
