### ISSUE TITLE
[TRANSLATION_HELP] Add a new language

### ISSUE THREAD

**Issue by elSolus** [mateusz-bak/openreads#537]
Hello. Straight to the point, I like the app. Kudos. I want to help translate it into Punjabi (Gurmukhi script) as it is used in India. But that language is not there. Please tell me how can I add it or kindly add it for me. In case you are confused about the language, this will help you: https://en.wikipedia.org/wiki/Punjabi_language

Thank you.

**Comment by mateusz-bak** [comment]
The language is added!
