### ISSUE TITLE
[FEATURE_REQUEST] Accessible Fonts

### ISSUE THREAD

**Issue by ELowry** [mateusz-bak/openreads#540]
**Is your feature request related to a problem? Please describe.**
The current font selector is a great feature for people with a variety of disabilities; however, the font selection does not appear to include any purpose-built accessibility-focused fonts.

**Describe the solution you'd like**
Here are two fonts that I know of and which could be a great addition to the app:

- [Atkinson Hyperlegible](https://brailleinstitute.org/freefont), a font designed for high legibility, especially for people with vision loss. (A more feature-rich version is available in the form of [Atkinson Hyperlegible Pro](https://jacobxperez.github.io/atkinson-hyperlegible-pro/))
- [OpenDyslexic](https://opendyslexic.org/) targets Dyslexia directly, and appears to be quite well regarded by many dyslexic people.

**Describe alternatives you've considered**
Another option would be to allow users to add their own font files to the app, allowing for any compatible font file to be used.

**Additional context**
N/A

**Comment by mateusz-bak** [comment]
Thanks for the great suggestion! Will be implemented in 2.7.0
