### ISSUE TITLE
[FEATURE_REQUEST] add translation options for KOREAN LANGUAGE please

### ISSUE THREAD

**Issue by Argoneon1810** [mateusz-bak/openreads#542]
Straight to the point, I'd like this app to have a korean language support. I will contribute to translating it. Please just open a slot for it.

I downloaded this app with misdirection that this could be an epub reader. Indeed, it was not, but at the same time, it surprised me since this could be a perfect replacement for leaving personal 'readers comment' with fancy UI. I was writing one with my samsung note, which is not really great-looking.

I am eager to use this, but since I will be writing in korean, I want the app to be showing in korean as well for cognitive consistency.

**Comment by mateusz-bak** [comment]
Hello @Argoneon1810 I'm glad that you like the app! Korean translation is now available

**Comment by Argoneon1810** [comment]
Korean translation is now 96% complete, and the suggestions for the rest of them are currently available. On the other hand, 5 check-failed strings are now revised, and ready to be updated. Yet, korean language is not visible in the app. I thought it would be network-fetching, but seems its not. Do I need to wait for next update? or is it necessary for me to build the app on my own?

**Comment by mateusz-bak** [comment]
The translations will be available with the next release 2.7.0
