### ISSUE TITLE
[FEATURE_REQUEST] Storygraph CSV import

### ISSUE THREAD

**Issue by joelchrono12** [mateusz-bak/openreads#544]
Storygraph has a CSV file that can't be imported to Openreads

Please add a way to import this file format

Also, newer versions of Bookwyrm include the start and finish dates for books so please improve that import too!

**Comment by mateusz-bak** [comment]
Thanks for raising the issue @joelchrono12 but we have ongoing request already here: https://github.com/mateusz-bak/openreads/issues/525

**Comment by joelchrono12** [comment]
My bad, still would be nice to improve the Bookwyrm CSV import, do I make a new issue for it?

**Comment by mateusz-bak** [comment]
Yeah @joelchrono12 and if you have the new CSV or documentation it would be great as I don't use Bookwyrm myself
