### ISSUE TITLE
[BUG] three strings have no option to translate

### ISSUE THREAD

**Issue by Argoneon1810** [mateusz-bak/openreads#559]
# issue
three strings in a certain popup has no option in the weblate to be translated

# how to replicate
1. create a new book, or enter existing book
2. enter editing mode
3. click capture reading, and click "set custom reading time"
4. day.title, hour.title and minute.title are not being translated, but yet on weblate, translation percentage is 100%

# desirable solution
let these three strings to have translation in the weblate

# Screenshot
![Screenshot_20240408_111906](https://github.com/mateusz-bak/openreads/assets/62126566/85842cc3-9b61-4cd0-92b1-7be04a5d1348)

**Comment by mateusz-bak** [comment]
Thanks for reporting, I'll correct this.
