### ISSUE TITLE
[UPDATE_ERROR] Cannot update the app (+screenshot)

### ISSUE THREAD

**Issue by elSolus** [mateusz-bak/openreads#562]
There has been days since 2.7.0 released but there is no update on F-Droid.
So I downloaded the apk package from here.
Surprisingly, none worked!
I tried all variants.
Almost all give me the same error (see s.shot below)

...
![openreads-update-error](https://github.com/mateusz-bak/openreads/assets/77105020/9302810f-204c-4fd8-a1a9-ab5e716e761b)
...

Why are updates on F-Droid so late?
Well, why none of these packages work?
Is there something I am missing?

**Comment by exstntlmsnthrp** [comment]
The app in Fdroid is built by them and not by the developer, so the timing is dependent on Fdroid.

The apps on Fdroid and GitHub are signed with different keys and are therefore incompatible with one another, even though they are the same version. 

You need to uninstall the app you have and install the other one in order for it to work. 

I'm using the GitHub version and I can confirm it works fine.

**Comment by elSolus** [comment]
@exstntlmsnthrp thanks a lot for the information. I didn't know that.
Also, Tuta app was installed from F-Droid but when I try to update next time from F-Droid, it said "signed with a different key" or something and did not update but it updated fine through Play St0re. Play St0re seems to have handled the signature different better. Anyway that was just a side story.

Coming to the point, do you know for sure if cloud backups done through the app include covers also? I mean if I uninstalled and installed again and restore the backup, will it bring back covers also?
Your input is appreciated. Thanks.

**Comment by mateusz-bak** [comment]
Hi @elSolus that's definitely the signing key issue. On GitHub release I use my private key, F-Droid uses it's own and on Google Play it's another key again(but that's optional, some apps can use the developer's private key.

I suggest then sticking to one release source.
Also the conflict might be when want to install a  specific architecture of the apk.

And yes, covers and challenges are exported in the cloud and local backups. In the CSV export they are not.

Closing the ticket, but please reach out if needed.

**Comment by elSolus** [comment]
Normally, I could have waited for F-Droid to publish the new update but as you may know I just translated the app into **Punjabi**, I was curious to see it in action and see where correction is needed as one can correctly translate when they know the actual context. But anyway,
Thanks a ton, mate. God bless you.
