### ISSUE TITLE
[FEATURE_REQUEST] upload to Open Library

### ISSUE THREAD

**Issue by Martinligabue** [mateusz-bak/openreads#587]
**Is your feature request related to a problem? Please describe.**
I am adding books locally manually when not available in ol. 

**Describe the solution you'd like**
It would be nice if there was a way to upload missing entries in ol

**Describe alternatives you've considered**
Direct upload seems unfeasible, so a guide for exporting in a format that ol likes, and how to do it, would be nice 

**Additional context**
N/A

**Comment by lymnyx** [comment]
@Martinligabue Hi, you seem to be asking for the same thing as #85 . If that is the case, you might want to close this issue and instead add your considered alternative to the existing thread.

**Comment by Martinligabue** [comment]
yes thanks, it seem I didn't find it or I searched wrongly
