### ISSUE TITLE
Provide goodreads

### ISSUE THREAD

**Issue by Sarat-1997** [mateusz-bak/openreads#588]
When I had searched a book or scan a book using ISBN with openreads api the result shows not found. Can you please provide goodreads api in this project?

**Comment by Gildas-GH** [comment]
Goodreads doesn't provide an API to get it's content. It was shut down a few years ago. And the developer doesn't want to add any proprietary sources at this stage (see https://github.com/mateusz-bak/openreads/issues/90#issuecomment-1722339001).
