### ISSUE TITLE
Update API

### ISSUE THREAD

**Issue by Sarat-1997** [mateusz-bak/openreads#599]
@mateusz-bak please update API we need to get all books while searching and using scanning. Kindly update the API ASAP.

**Comment by Arnvidr** [comment]
Is this about the Open Library search? It seems to have stopped working sometime in the last two weeks.

**Comment by Sarat-1997** [comment]
@Arnvidr  Yes bro. Before all it works perfectly. But as of now when I had searched it it took too much time to load and showing the error message. Anyways thanks for the update.

**Comment by adsadownloads** [comment]
Same on my end. 

Visiting the https://openlibrary.org/ domain returns an error for me. Could it be because of this? Does the site load for anybody?

**Comment by adsadownloads** [comment]
> Is this about the Open Library search? It seems to have stopped working sometime in the last two weeks.

The https://openlibrary.org/ domain won't load for me. Are the errors just from open library servers being down?

**Comment by Arnvidr** [comment]
That seems likely. It seems like it is down because of the lawsuits against the Internet Archive. Who knows when or if it ever comes back online...

**Comment by bicolino34** [comment]
Open Library is down due to recent hacking of Internet Archive. The team is working on getting it back

**Comment by Sarat-1997** [comment]
@Arnvidr @bicolino34 any update. Is this fixed?

**Comment by bicolino34** [comment]
Main site of Internet Archive seems to be back online. Open Library might follow it soon, although it is still offline as of 21 October

**Comment by mateusz-bak** [comment]
Closing and moving discussion to #601
